### ISSUE TITLE
adding wdi data to r

### ISSUE THREAD

**Issue by haisuh** [haisuh/CO2Cancer_Project#1]
@AaronGullickson adding wdi data to r is done. thanks for demonstrating the data harvesting process in class. please review.

**Comment by AaronGullickson** [comment]
@haisuh This looks good. There is really no need to read in the "Definitions and Source" file - that is just documentation. Also be sure to use the README.md in the input folder to document your data source.

The only other suggestion I have would be that you might want to consider some other control variables (like GDP per capita, urbanization, etc.) in your models.

**Comment by haisuh** [comment]
@AaronGullickson thanks for your feedback. added gdp and urban data, and data source description in readme in input folder. did not read in the "definition" file this time. please review.

**Comment by AaronGullickson** [comment]
@haisuh I see the changes to the `organize_data.R` script but it does not look like you committed and pushed up the new data.

**Comment by haisuh** [comment]
@AaronGullickson new data committed and pushed. a warning showed up before committing data, saying data file size (315KB) may cause rstudio to slow down or hang. the data file size increased by 156KB after new variables are added. seeing no noticeable error in data, i committed anyway.

**Comment by AaronGullickson** [comment]
@haisuh I see the datasets, but you actually have two datasets in the input directory. Please delete the one you are no longer using to avoid confusion.
