### ISSUE TITLE
error when knitting to html 

### ISSUE THREAD

**Issue by haisuh** [haisuh/CO2Cancer_Project#3]
@AaronGullickson failed to knit to html. pushed "analysis.Rmd." please help. 
warning message as below:

processing file: analysis.Rmd
(*) NOTE: I saw chunk options "figure echo=FALSE"
 please go to https://yihui.name/knitr/options
 (it is likely that you forgot to quote "character" options)
Error in parse(text = code, keep.source = FALSE) : 
  <text>:1:15: unexpected symbol
1: alist( figure echo
                  ^
Calls: <Anonymous> ... parse_params -> withCallingHandlers -> eval -> parse_only -> parse
Execution halted

**Comment by AaronGullickson** [comment]
Two problems:

1. You don't have a comma after the name of the code chunk and `echo=FALSE`.  Also the name of your last code chunk may be problematic. Don't use spaces. 

2. You need to include `library(ggplot2)` in your setup code chunk.

**Comment by haisuh** [comment]
@AaronGullickson added comma, deleted space in code chunks. included ggplot 2 in library. knitting to html was successful. Thanks.
