### ISSUE TITLE
error when knitting to pdf

### ISSUE THREAD

**Issue by haisuh** [haisuh/CO2Cancer_Project#4]
@AaronGullickson (1) having trouble running the set up code chuck which works finely in analysis.Rmd. why wouldn't it run in main.Rmd? (2) would love to be able to add a header like "figure 1" or "figure 2" to each figure but I don't know how. Right now, all figures are kind of crammed together, which is not an efficient way to read. please help, thanks.

**Comment by AaronGullickson** [comment]
@haisuh See [my announcement](https://canvas.uoregon.edu/courses/133660/discussion_topics/556327) on Canvas yesterday. Get rid of the `source("useful_functions.R")` line and change the pathway to your data in the load command:

```r
load("../../analysis/output/analytical_data.RData")
```

**Comment by AaronGullickson** [comment]
On the figure issue, you can include in the code chunk header (the curly brackets) the following command, separated by commas:

```
fig.cap="My figure caption"
```

This will add a caption and a figure number to the final pdf.

**Comment by haisuh** [comment]
@AaronGullickson 
1 the set up chuck seems to run finely now. thanks.
2 one new error came up in line 161 - cannot find lm_mi function. confused because this table runs smoothly in analysis.Rmd. help please.
3 adding figure number to chart - I now separate each ggplot with "```{r fig.cap="Figure 8", echo=FALSE}" in the code chuck header, 8 meaning the 8th chart. There are 8 charts in total. Is this correct?

**Comment by AaronGullickson** [comment]
@haisuh 

`lm_mi` is a custom function we created in `analysis.Rmd`. To get it to work in `main.Rmd` you need to copy over the `functions` code chunk from `analysis.Rmd` and put it before the code chunk that calls `lm_mi`. 

There is no need to put "Figure #" as the caption. When R knits to PDF it will attach that exact title tot the figure caption, so this will come out as "Figure 8: Figure 8". Use the `fig.cap` argument to write the part that comes after the colon.
